services:
  - type: web
    name: hot-or-not
    env: python
    buildCommand: pip install -r requirements.txt && sudo apt-get update && sudo apt-get install libomp-dev && sudo apt-get install ffmpeg
    startCommand: python app.py
    plan: free
    pythonVersion: 3.9.6
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: NUMBA_CACHE_DIR
        value: "/tmp/numba_cache"
      - key: LIBROSA_CACHE_DIR
        value: "/tmp/librosa_cache"
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    healthCheckPath: /
    autoDeploy: false
    buildFilter:
      paths:
        - requirements.txt
        - "**/*.py"
        - "**/*.pb"
        - models/**
        - essentia graphfiles/**